forum_app/urls.py
from django.urls import path
from forum_app import views

app_name = 'forum_app'

urlpatterns = [
    path('', views.forum, name='forum'),
    path('add_post/', views.add_post, name='add_post'),
    path('<int:id>/', views.view_post, name='view_post'),
    path('<int:id>/add_reply/', views.reply_view, name='add_reply'),
]

globe_app/urls.py
from django.urls import path
from globe_app import views

app_name = 'globe_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register_contd/', views.register_contd, name='register_contd'),
    path('profile/<username>/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('find_buddy/', views.find_buddy, name='find_buddy'),

    # Upcoming Travels
    path('upcoming_travels/<owner>/', views.upcoming_travels, name='upcoming_travels'),
    path('add_upcoming_travel/', views.add_upcoming_travel, name='add_upcoming_travel'),
    path('save_location/', views.save_location, name='save_location'),
    path('get_user_saved_locations/<user>/', views.get_user_saved_locations, name='get_user_saved_locations'),

    # Travel History
    path('travel_history/<owner>/', views.travel_history, name='travel_history'),
    path('add_history/', views.add_history, name='add_history'),
    path('save_history_location/', views.save_history_location, name='save_history_location'),
    path('get_user_saved_history_locations/<user>/', views.get_user_saved_history_locations, name='get_user_saved_history_locations'),

    # Travel Wishlist
    path('travel_wishlist/<owner>/', views.travel_wishlist, name='travel_wishlist'),
    path('add_wishlist/', views.add_wishlist, name='add_wishlist'),
    path('save_wishlist_location/', views.save_wishlist_location, name='save_wishlist_location'),
    path('get_user_saved_wishlist_locations/<user>/', views.get_user_saved_wishlist_locations, name='get_user_saved_wishlist_locations'),
    
    path('my_trips/', views.my_trips, name='my_trips'),
    path('search_users/', views.search_users, name='search_users'),

    # Messaging URLs
    path('inbox/', views.list_threads, name='inbox'),
    path('inbox/<int:pk>/', views.thread_view, name='thread'),
    path('inbox/<int:pk>/create_message/', views.create_message, name='create_message'),
    path('inbox/<username>/create_or_find_message_thread/<receiver>/', views.create_or_find_message_thread, name='create_or_find_message_thread'),

]

globetrotters_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from globe_app import views as globe_views
from forum_app import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class Registration(RegistrationView):
    def get_success_url(self, user):
        return reverse('globe_app:register_contd')
        # return reverse('user_app:register_contd')


urlpatterns = [
    path('', globe_views.index, name='index'),
    path('globetrotters/', include('globe_app.urls')),
    path('forum/', include('forum_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', Registration.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globe_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

maxCharLength = 128


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=maxCharLength)
    middle_name = models.CharField(max_length=maxCharLength, blank=True)
    surname = models.CharField(max_length=maxCharLength)
    age = models.IntegerField()
    description = models.TextField(blank=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('NB', 'Non Binary'),
        ('PNTD', 'Prefer not to say'),
    )
    gender = models.CharField(max_length=4, choices=GENDER_CHOICES, blank=True)
    picture = models.ImageField(upload_to='profilePics', blank=True)


    def __str__(self):
        return self.user.username


class Destination(models.Model):
    locationName = models.CharField(max_length=maxCharLength)
    longitude = models.FloatField(default=0.0)
    latitude = models.FloatField(default=0.0)

    def __str__(self):
        return self.locationName

# class TravelNote(models.Model):
#     # owner = models.ForeignKey(User)
#     content = models.TextField(blank=True)
#     destination = models.ForeignKey(Destination, on_delete=models.CASCADE, blank=True)
#     # travelPics = models.ImageField(upload_to="travelPics", blank=True)

#     def __str__(self):
#         return self.content


class TravelHistory(models.Model):
    owner = models.CharField(null=False, max_length=maxCharLength, blank=False, default='')
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    # travelPics = models.ImageField(upload_to="travelPics", blank=True)
    travelNotes = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Travel Histories'

    def __str__(self):
         return self.destination.locationName + " - " + self.owner
    
class TravelWishlist(models.Model):
    owner = models.CharField(max_length=maxCharLength)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    travelNotes = models.TextField(blank=True)

class UpcomingTravel(models.Model):
    owner = models.CharField(null=False, max_length=maxCharLength, blank=False)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    dateStart = models.DateField()
    dateEnd = models.DateField()
    budgetStart = models.DecimalField(max_digits=6, decimal_places=2)
    budgetEnd = models.DecimalField(max_digits=6, decimal_places=2)

    DATE_FLEX_CHOICES = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    dateFlexibility = models.CharField(max_length=2, choices=DATE_FLEX_CHOICES, blank=True)
    travelNotes = models.TextField(blank=True)

    def __str__(self):
        return self.destination.locationName        



# class ForumPost(models.Model):
#     title = models.CharField(max_length=maxCharLength)
#     date = models.DateField(default=timezone.now) 
#     content = models.TextField()

# class PostReply(models.Model):
#     post = models.ForeignKey(ForumPost, on_delete=models.CASCADE)
#     title = models.CharField(max_length=maxCharLength)
#     date = models.DateField(default=timezone.now) 
#     content = models.TextField()

#     class Meta:
#         verbose_name_plural = 'PostReplies'


# Messaging Functionality

class MessageThread(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)

class Message(models.Model):
    messageThread = models.ForeignKey('MessageThread', on_delete=models.CASCADE, blank = True, related_name='+')
    messageSender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    messageReceiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    content = models.TextField(max_length=1000)
    date = models.DateTimeField(default=timezone.now)
    messageRead = models.BooleanField(default=False)

    def __str__(self):
        return "from: " + self.messageSender.username + " to:" + self.messageReceiver.username + " messageRead: " + str(self.messageRead)

templates/globe_templates/add_history.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Add destination to History
{% endblock %}


{% block content_block %}
{% if user.is_authenticated %}
<div class="container_green">
    <br/>
    <h5>Add a destination to your travel history by putting it in the search bar on the map</h5>
    <div id="map"></div> <br /><br />
</div>

<script>
    mapboxgl.accessToken = 'pk.eyJ1IjoidmFsYm9yZ2pvaGFubmVzZW4iLCJhIjoiY2w1czlxdTg1MDJqMjNpbXIzMmE3Z2ZpMSJ9.KhJK2veJjqe6FZ4YtnKkSw';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        projection: 'naturalEarth',
        zoom: 0.75
    });

    // Search box for locations (countries, cities, addresses etc)
    let myMap = map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl,
        })
    );

    function saveHistoryLocation() {
        console.log(map._markers);
        let latitude, longitude, locationFullName;
        console.log('HERE!');
        try {
            latitude = map._markers[0]._lngLat.lat;
            longitude = map._markers[0]._lngLat.lng;
            locationFullName = $('.mapboxgl-ctrl-geocoder--input')[0].value; // jQuery to get the name of location
        } catch (e) {
            $("#error_message_text").text('Please search for a location before submitting.');
        }

        console.log('HERE 2!');
        // let travelPics = $('#travel_pic').attr('src', '{{ MEDIA_URL }}');
        let noteContent = $('#travel_note').val();
        let owner = "{{user}}";
        console.log('HERE 3!');

        if (!locationFullName || !latitude || !longitude) {
            $("#error_message_text").text('Please check that you added a location.');
            console.log('error message')
            return;
        }

        let csrfToken = document.cookie.split('=')[1]; // grab the csrf token from the cookies
        // ajax request to send the coordinates to the backend
        $.ajax({
            type: "POST",
            url: "{% url 'globe_app:save_history_location' %}",
            headers: { 'X-CSRFToken': csrfToken },
            data: {
                'latitude': latitude,
                'longitude': longitude,
                'locationFullName': locationFullName,
                'owner': owner,
                // 'travelPics': travelPics,
                'noteContent': noteContent,
            },
            // success and error are callbacks. They notify when the request is done.
            success: function (response) {
                console.log(response);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log('failed');
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
            }
        });
    }
    
</script>
<div class="content_centre"> <br/>
    <div><h5>You can add a picture or notes relating to the trip you were on</h5><br/>
    {% if user.is_authenticated %}
            {% csrf_token %}
            <!-- <input type="hidden"/> -->
            {{ form.as_p }}
            {{ form.media }}
            <br />
            <button class="btn btn-outline-success" type="button" name="submit" enctype="multipart/form-data"
                onclick="saveHistoryLocation()">
                Add To Travel History
            </button>
            <br/><span id="error_message_text" style="color: red;"></span>
        {% endif %}
    </div>


    <br/>
    <a class="btn btn-info" role="button" href="{% url 'globe_app:travel_history' user %}">Return to Travel History</a><br/><br/>
    {% else %}
        <br />
            <h2>You must be registered or logged in to add to your upcoming travels.</h2><br /><br />
    {% endif %}
</div>
{% endblock %}

templates/globe_templates/add_upcoming_travel.html
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
Add Location to Upcoming
{% endblock %}

{% block content_block %}
{% if user.is_authenticated %}

<div class="container_green">
    <br/>
    <h5>Add a destination to upcoming trips by putting it in the search bar on the map</h5>
    <div id="map" ></div> <br /><br />
</div>

<script>
    // Instantiate the map
    mapboxgl.accessToken = 'pk.eyJ1IjoidmFsYm9yZ2pvaGFubmVzZW4iLCJhIjoiY2w1czlxdTg1MDJqMjNpbXIzMmE3Z2ZpMSJ9.KhJK2veJjqe6FZ4YtnKkSw';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        projection: 'naturalEarth',
        zoom: 0.75
    });

    // Search box for locations (countries, cities, addresses etc)
    // Provides geocoding functionality
    let myMap = map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl,
        })
    );

    // save the location information to the backend from Mapbox API
    function saveLocation() {
        console.log(map._markers);
        let latitude, longitude, locationFullName;

        try {
            latitude = map._markers[0]._lngLat.lat;
            longitude = map._markers[0]._lngLat.lng;
            locationFullName = $('.mapboxgl-ctrl-geocoder--input')[0].value; // jQuery to get the name of location
        } catch (e) {
            $("#error_message_text").text('Please search for a location before submitting.');
        }

        // the following are values input into the form boxes
        // To ensure all the data was grouped together, the form data was acquired this way along with the coordinates and location name above.

        let dateStart = $('#date_start').val();
        let dateEnd = $('#date_end').val();
        let budgetStart = $('#budget_start').val();
        let budgetEnd = $('#budget_end').val();
        let owner = "{{user}}";
        let noteContent = $('#travel_note').val();

        if (!locationFullName || !latitude || !longitude) {
            $("#error_message_text").text('Please check that you added a location.');
            console.log('error message')
            return;
        }

        let csrfToken = document.cookie.split('=')[1]; // grab the csrf token from the cookies
        // ajax request to send the coordinates to the backend
        $.ajax({
            type: "POST",
            url: "{% url 'globe_app:save_location' %}",
            headers: { 'X-CSRFToken': csrfToken },
            data: {
                'latitude': latitude,
                'longitude': longitude,
                'locationFullName': locationFullName,
                'dateStart': dateStart,
                'dateEnd': dateEnd,
                'budgetStart': budgetStart,
                'budgetEnd': budgetEnd,
                'owner': owner,
                'noteContent': noteContent,
            },
            // success and error are callbacks. They notify when the request is done.
            success: function (response) {
                console.log(response);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log('failed');
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
            }
        });
    }

</script>

<!-- upcoming travel form -->
<div class="content_centre"> <br/>
    <div>
        {% if user.is_authenticated %}
            {% csrf_token %}
            <input type="hidden" />
            {{ form.as_p }}
            {{ form.media }}
            <br />
            <button class="btn btn-outline-success" type="button" name="submit"
                onclick="saveLocation()">
                Add To Upcoming Trips
            </button>
            <br/><span id="error_message_text" style="color: red;"></span>
        {% endif %}
    </div>

    <script>
        $("#date_start").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#date_end").datepicker({ dateFormat: 'yy-mm-dd' });
    </script>

    <br/>
    <a class="btn btn-info" role="button" href="{% url 'globe_app:upcoming_travels' user %}">Return to Upcoming Trips</a><br/><br/>
{% else %}
<br />
    <h2>You must be registered or logged in to add to your upcoming travels.</h2><br /><br />

{% endif %}
</div>

{% endblock %}

templates/globe_templates/add_wishlist.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Add destination to Travel Wishlist
{% endblock %}


{% block content_block %}
{% if user.is_authenticated %}

<div class="container_green">
    <br/>
    <h5>Add a destination to your travel wishlist by putting it in the search bar on the map</h5>
    <div id="map"></div> <br /><br />
</div>

    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoidmFsYm9yZ2pvaGFubmVzZW4iLCJhIjoiY2w1czlxdTg1MDJqMjNpbXIzMmE3Z2ZpMSJ9.KhJK2veJjqe6FZ4YtnKkSw';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            projection: 'naturalEarth',
            zoom: 0.75
        });

        // Search box for locations (countries, cities, addresses etc)
        let myMap = map.addControl(
            new MapboxGeocoder({
                accessToken: mapboxgl.accessToken,
                mapboxgl: mapboxgl,
            })
        );

        function saveWishlistLocation() {
            console.log(map._markers);
            let latitude = map._markers[0]._lngLat.lat;
            let longitude = map._markers[0]._lngLat.lng;
            let locationFullName = $('.mapboxgl-ctrl-geocoder--input')[0].value; // jQuery to get the name of location
            // the following are values input into the form boxes

            let noteContent = $('#travel_note').val();
            let owner = "{{user}}";

            if (!locationFullName || !latitude || !longitude) {
                return;
            }

            let csrfToken = document.cookie.split('=')[1]; // grab the csrf token from the cookies
            $.ajax({
                type: "POST",
                url: "{% url 'globe_app:save_wishlist_location' %}",
                headers: { 'X-CSRFToken': csrfToken },
                data: {
                    'latitude': latitude,
                    'longitude': longitude,
                    'locationFullName': locationFullName,
                    'owner': owner,
                    'noteContent': noteContent,
                },
                // success and error are callbacks. They notify when the request is done.
                success: function (response) {
                    console.log(response);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('failed');
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
        }
        
    </script>

<div class="content_centre"> <br/>
    <div><h5>You can add notes relating to the trip</h5><br/>
        {% if user.is_authenticated %}
            {% csrf_token %}
            <!-- <input type="hidden"/> -->
            {{ form.as_p }}
            {{ form.media }}
            <br />
            <button class="btn btn-outline-success" type="button" name="submit" enctype="multipart/form-data"
                onclick="saveWishlistLocation()">
                Add To Travel Wishlist
            </button>
        {% endif %}
    </div>
    <br />
    <a class="btn btn-info" role="button" href="{% url 'globe_app:travel_wishlist' user %}">Return to Travel Wishlist</a><br/><br/>
    {% else %}
        <br />
            <h2>You must be registered or logged in to add to your travel wishlist.</h2><br /><br />
    {% endif %}
</div>
{% endblock %}

templates/globe_templates/find_buddy.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
Find Buddy
{% endblock %}

{% block content_block %}
<div class="container_green">
    <!-- <div class="row"> -->
        <div class="text-center" style="background-color: #abe0bc">
            <div class="bg-image" 
            style="background-image: url({% static 'images/findbuddy.jpeg' %});background-size: cover;">
                <form method="get" style="padding-top: 55px;">
                    <p style="margin-right: 25px;margin-bottom: 15px;">
                        {{ myFilter.form.destination.label }}: {{ myFilter.form.destination }} <br/>
                    </p>
                    <p style="margin-right: 25px;margin-bottom: 15px;">
                        {{ myFilter.form.dateStart.label }}: {{ myFilter.form.dateStart }}
                        {{ myFilter.form.dateEnd.label }}: {{ myFilter.form.dateEnd }} <br/>
                    </p>
                    <p style="margin-right: 25px;margin-bottom: 15px;">
                        {{ myFilter.form.budgetStart.label }}: {{ myFilter.form.budgetStart }}
                        {{ myFilter.form.budgetEnd.label }}: {{ myFilter.form.budgetEnd }}
                    </p>
                    <button class="btn btn-success" style="opacity: 0.8;" type="submit">
                        Search for Buddy
                    </button>
                </form> 
            <br /><br />
            </div>
        </div>
    <!-- </div> -->
</div>
<div class="container_green"><br/>
    <div class="row mb-3 justify-content-center">
        <div class="card col-6 text-center p-3 shadow-sm" style="width: 95%;background-color: #688be95c;height: 100%;
        position: relative;">
            {% if trips %}
            <br/>
                <center><h4>Results</h4></center>
                <div style="display: flex;flex-flow: wrap;">
                    {% for trip in trips %}
                    <div class="col-sm-4">
                        <br/>
                        
                        <div class="card text-center col-12 p-3 shadow-sm" style="min-height: 305px;">
                            <h5 class="card-header text-center col-12 text-center"><strong><a href="{% url 'globe_app:profile' trip.owner %}" style="color: #212529;">{{ trip.owner }}</a></strong></h5>
                            <ul style="list-style-type: none;">
                                <p class="card-text">
                                    <li>Going to: {{ trip.destination }}</li>
                                    <li>From: {{ trip.dateStart }}</li>
                                    <li>To: {{ trip.dateEnd }}</li>
                                    <li>Daily budget from: £{{ trip.budgetStart }}</li>
                                    <li>Daily budget to: £{{ trip.budgetEnd }}</li>
                                    <li><a class="btn btn-outline-success" role="button" href="{% url 'globe_app:create_or_find_message_thread' user trip.owner %}">Message {{ trip.owner }}</a></li>
                                </p>
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                There are currently no trips planned
            {% endif %}
        </div>
    </div>

<script>
    $("#id_dateStart").datepicker({ dateFormat: 'yy-mm-dd' });
    $("#id_dateEnd").datepicker({ dateFormat: 'yy-mm-dd' });
</script>

</div>
{% endblock %}

templates/globe_templates/my_trips.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    My Trips
{% endblock %}

{% block content_block %}
<div class="container_green">
    <br/><h4>{{ user.username }}'s Trips</h4> <br/><br/>

    <a href="{% url 'globe_app:upcoming_travels' user.username %}"
    class="btn btn-success btn-lg active" role="button" aria-pressed="true">Upcoming Trips</a>
    <hr/>
    <a href="{% url 'globe_app:travel_history' user.username %}"
    class="btn btn-danger btn-lg active" role="button" aria-pressed="true">Travel History</a>
    <hr/>
    <a href="{% url 'globe_app:travel_wishlist' user.username %}" 
    class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Travel Wishlist</a>
    <br/><br/><br/>
</div>
{% endblock %}

templates/globe_templates/search_users.html
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Search Results
{% endblock %}

{% block content_block %}



<div class="container_green"><br/>
    <h2>Results for {{searched}}</h2> <br />
    <div class="row mb-3 justify-content-center">
        <div class="card col-6 text-center p-3 shadow-sm ">
            {% if searched %}
                {% for searchedUser in users %}
                <h5 class="card-header text-center col-12 text-center"><strong>
                    <a href="{% url 'globe_app:profile' searchedUser %}">{{ searchedUser }}</a></strong></h5>
                <div class="card text-center col-12 p-3 shadow-sm">
                    <ul style="list-style-type: none;">
                        {% if searchedUser.picture %}
                            <img src="{{ MEDIA_URL }}{{ searchedUser.picture }}" alt="{{ searchedUser }}'s profile picture " /><br />
                        {% endif %}
                        <li>User: <a href="{% url 'globe_app:profile' searchedUser %}">{{ searchedUser }}</a></li>
                        <li><a href="{% url 'globe_app:create_or_find_message_thread' user searchedUser %}">Message {{ searchedUser }}</a></li>
                        <li>Age: {{ searchedUser.age }}</li>
                        <li>Gender: {{ searchedUser.gender }}</li>
                        <li>Description: {{ searchedUser.description }}</li>
                    </ul>
                </div>
                {% endfor %}

            {% else %}
                <h2>Please enter a user to search for</h2>

            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/globe_templates/user_profile.html
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
{{ user_profile.first_name }}'s Profile
{% endblock %}

{% block content_block %}
<div class="container_green_left">
    <div class="row">
        <div class="col mt-3 l-1">
            {% if user_profile.picture %}
            <center><img src="{{ MEDIA_URL }}{{ user_profile.picture }}" alt="{{ user.username }}'s profile picture " style="width: 400px;height: 300px;border-radius: 30%;" /><br /></center>
            {% endif %}
        </div>
        <div class="col mt-4">
            <ul style="list-style-type: none;">
                <li>
                    <h1>{{ user_profile.first_name }} {{user_profile.middle_name }} {{ user_profile.surname }}</h1>
                </li>
                <li><a class="btn btn-success" role="button" href="{% url 'globe_app:create_or_find_message_thread' user user_profile %}">Message {{ user_profile.first_name }}</a></li><br/>
                <li><strong>Age:</strong> {{ user_profile.age }}</li>
                <li><strong>About {{ user_profile.first_name }}:</strong> <div class="card col-8 p-3">{{ user_profile.description }}</div></li>
            </ul>
        </div>
    </div>
    <br/><br/>
</div>

{% endblock %}

{% block white_content_block %}

<div class="content_centre"><br/>
    <h4>{{ user.username }}'s Trips</h4> <br/><br/>
    <a href="{% url 'globe_app:upcoming_travels' user.username %}"
    class="btn btn-success" role="button" aria-pressed="true">Upcoming Travels</a>

    
    <a href="{% url 'globe_app:travel_history' user.username %}"
    class="btn btn-dark" role="button" aria-pressed="true">Travel History</a>

    <a href="{% url 'globe_app:travel_wishlist' user.username %}" 
    class="btn btn-light" role="button" aria-pressed="true">Travel Wishlist</a>


    <div id="map"></div>

    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoidmFsYm9yZ2pvaGFubmVzZW4iLCJhIjoiY2w1czlxdTg1MDJqMjNpbXIzMmE3Z2ZpMSJ9.KhJK2veJjqe6FZ4YtnKkSw';
        var savedMap = new mapboxgl.Map({
            container: 'map',
            // projection: 'globe',
            style: 'mapbox://styles/mapbox/streets-v11',
            projection: 'naturalEarth',
            zoom: 0.75
        });
    
        function getLocations() {

            let csrfToken = document.cookie.split('=')[1]; // grab the csrf token from the cookies
            // ajax request to send the coordinates to the backend
            $.ajax({
                type: "GET",
                url: "{% url 'globe_app:get_user_saved_locations' user %}",
                headers: { 'X-CSRFToken': csrfToken },
                // success and error are callbacks. They notify when the request is done.
                success: function (response) {
                    console.log(response);
                    response.locationList.forEach(element => {
                        new mapboxgl.Marker({ color: '#8fd5a6' })
                            .setLngLat([element[0], element[1]])
                            .addTo(savedMap)
                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('failed');
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
        }

        document.addEventListener("load", getLocations());
    
        function getHistoryLocations() {
            let csrfToken = document.cookie.split('=')[1]; // grab the csrf token from the cookies
            // ajax request to send the coordinates to the backend
            $.ajax({
                type: "GET",
                url: "{% url 'globe_app:get_user_saved_history_locations' user %}",
                headers: { 'X-CSRFToken': csrfToken },
                // success and error are callbacks. They notify when the request is done.
                success: function (response) {
                    console.log(response);
                    response.locationHistoryList.forEach(element => {
                        new mapboxgl.Marker({ color: 'black' })
                            .setLngLat([element[0], element[1]])
                            .addTo(savedMap)
                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('failed');
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
            }
    
            document.addEventListener("load", getHistoryLocations());


        function getWishlistLocations() {
            let csrfToken = document.cookie.split('=')[1]; // grab the csrf token from the cookies
            // ajax request to send the coordinates to the backend
            $.ajax({
                type: "GET",
                url: "{% url 'globe_app:get_user_saved_wishlist_locations' user %}",
                headers: { 'X-CSRFToken': csrfToken },
                // success and error are callbacks. They notify when the request is done.
                success: function (response) {
                    console.log(response);
                    response.locationWishlistList.forEach(element => {
                        new mapboxgl.Marker({ color: 'lightgrey' })
                            .setLngLat([element[0], element[1]])
                            .addTo(savedMap)
                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('failed');
                    console.log(jqXHR);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
            }


            document.addEventListener("load", getWishlistLocations());
    </script>


</div>
{% endblock %}