forum_app/urls.py
from django.urls import path
from forum_app import views

app_name = 'forum_app'

urlpatterns = [
    path('', views.forum, name='forum'),
    path('add_post/', views.add_post, name='add_post'),
    path('<int:id>/', views.view_post, name='view_post'),
    path('<int:id>/add_reply/', views.reply_view, name='add_reply'),
]

globe_app/urls.py
from django.urls import path
from globe_app import views

app_name = 'globe_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register_contd/', views.register_contd, name='register_contd'),
    path('profile/<username>/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('find_buddy/', views.find_buddy, name='find_buddy'),

    # Upcoming Travels
    path('upcoming_travels/<owner>/', views.upcoming_travels, name='upcoming_travels'),
    path('add_upcoming_travel/', views.add_upcoming_travel, name='add_upcoming_travel'),
    path('save_location/', views.save_location, name='save_location'),
    path('get_user_saved_locations/<user>/', views.get_user_saved_locations, name='get_user_saved_locations'),

    # Travel History
    path('travel_history/<owner>/', views.travel_history, name='travel_history'),
    path('add_history/', views.add_history, name='add_history'),
    path('save_history_location/', views.save_history_location, name='save_history_location'),
    path('get_user_saved_history_locations/<user>/', views.get_user_saved_history_locations, name='get_user_saved_history_locations'),

    # Travel Wishlist
    path('travel_wishlist/<owner>/', views.travel_wishlist, name='travel_wishlist'),
    path('add_wishlist/', views.add_wishlist, name='add_wishlist'),
    path('save_wishlist_location/', views.save_wishlist_location, name='save_wishlist_location'),
    path('get_user_saved_wishlist_locations/<user>/', views.get_user_saved_wishlist_locations, name='get_user_saved_wishlist_locations'),
    
    path('my_trips/', views.my_trips, name='my_trips'),
    path('search_users/', views.search_users, name='search_users'),

    # Messaging URLs
    path('inbox/', views.list_threads, name='inbox'),
    path('inbox/<int:pk>/', views.thread_view, name='thread'),
    path('inbox/<int:pk>/create_message/', views.create_message, name='create_message'),
    path('inbox/<username>/create_or_find_message_thread/<receiver>/', views.create_or_find_message_thread, name='create_or_find_message_thread'),

]

globetrotters_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from globe_app import views as globe_views
from forum_app import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class Registration(RegistrationView):
    def get_success_url(self, user):
        return reverse('globe_app:register_contd')
        # return reverse('user_app:register_contd')


urlpatterns = [
    path('', globe_views.index, name='index'),
    path('globetrotters/', include('globe_app.urls')),
    path('forum/', include('forum_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', Registration.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/forum_templates/add_post.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Globetrotter Add Post
{% endblock %}

{% block content_block %}
{% if user.is_authenticated %}
    <div class="container_green">
        <br/>
        <div class="row">
            <form role="form" id="post_form" method="post"
            action="{% url 'forum_app:add_post' %}">
                {{form.as_p}}
                {% csrf_token %}

                <button class="btn btn-success">
                    Add Post
                </button> 
            </form> 
        </div><br/>
    </div>
{% endif %}
{% endblock %}

templates/forum_templates/add_reply.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Post: {{ post.title }}
{% endblock %}

{% block content_block %}
{% if user.is_authenticated %}
    <div class="container_green_standard"><br/>
        <div class="row mb-3 justify-content-center">
            <div class="card col-10 text-center p-3 shadow-sm ">
                <h4 class="card-header text-center col-12 text-center">
                    {{ post_title }}<br/></h4>
                    <div class="card text-center col-12 p-1 shadow-sm">
                    <p class="card-text">
                        <h5>{{ post_content|linebreaks }}</h5>
                    </p>
                </div>
            </div>
        </div> 
        <form role="form" method="post" action="{% url 'forum_app:add_reply' post_id %}">
            {{ form.as_p }}
            {% csrf_token %}

            <button class="btn btn-success">
                Submit comment
            </button> <br />
        </form>

        <br/><br/><br/>     
    </div>
{% endif %}

{% endblock %}

templates/forum_templates/forum.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Globetrotter Forum
{% endblock %}

{% block content_block %}

<div class="container_white">
    <center><a href="{% url 'forum_app:add_post' %}" class="btn btn-success" 
        role="button" aria-pressed="true" style="position: absolute;
        right: 5px;
        top: 10%;
        z-index: 1;">Add Post</a> </center> 
    <div class="bg-image" 
        style="background-image: url({% static 'images/forum.jpeg' %});background-size: cover;height:693px;">
        <div class="row mb-3 justify-content-center" style="    position: relative;overflow: hidden;
        height: 100%;">
            <div class="card col-6 text-center p-3 shadow-sm" style="opacity: 0.9; overflow-y: scroll;height: 100%;width: 80%;">
                <center><h4>Current posts: </h4></center>
                {% if post_list %}
                <div  style="display: flex;flex-flow: wrap;">
                    {% for post in post_list %}<br/>
                    <div class="col-sm-6">
                        <h5 class="card-header text-center col-12 text-center"><strong><a style="color: #212529;" href="/forum/{{ post.id }}">{{ post.title }} </a></strong></h5>
                        <div class="card text-center col-12 p-1 shadow-sm">
                            <ul style="list-style-type: none;">
                                <div class="card-text">
                                    <p>{{ post.timestamp }}</p>
                                    <p>by {{ post.writer.username }}</p>
                                </div>
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                    There are no posts currently.
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/forum_templates/view_post.html
<!DOCTYPE html>
{% extends 'globe_templates/base.html' %}
{% load static %}


{% block title_block %}
    Post: {{ post.title }}
{% endblock %}

{% block content_block %}





<div class="container_green_standard"><br/>
    <div class="row mb-3 justify-content-center">
        <div class="card col-10 text-center p-3 shadow-sm ">
            <h4 class="card-header text-center col-12 text-center">
                {{ post.title }}<br/></h4>
                <div class="card text-center col-12 p-1 shadow-sm">
                <p class="card-text">
                    <h5>{{ post.content|linebreaks }}</h5>
                </p>
                <div style="display:flex;">
                    <div style="text-align: left;" class="col-sm-6">
                        <a style="color: #212529;" href="{% url 'globe_app:profile' post.writer %}">{{ post.writer }}</a>
                    </div>
                    <div style="text-align: right;color:grey;" class="col-sm-6">{{ post.timestamp }}</div>
                </div>
            </div>
        </div>
    </div> 
    <a href="{% url 'forum_app:add_reply' post.id %}" class="btn btn-success" 
        role="button" aria-pressed="true">Add Comment</a> <br/><br/>


    <center><strong>Comments</strong></center>
    <div class="row mb-3 justify-content-center">
        <div class="card col-6 text-center p-3 shadow-sm ">
        {% if post_replies %}
            {% for reply in post_replies %}
            <div class="card">
                    <p class="card-text">
                        {{ reply.content }} <br/> <br/> 
                    </p>
                    
                <div style="display:flex;padding: 0 5px;">
                    <div style="text-align: left;" class="col-sm-6">
                        <a style="color: #212529;" href="{% url 'globe_app:profile' post.writer %}">{{ reply.reply_writer }}</a>
                    </div>
                    <div style="text-align: right;color:grey;" class="col-sm-6">{{ reply.timestamp }}</div>
                </div> 
            </div><br/>
            {% endfor %}
        {% else %}
            There are no comments for this post.
        {% endif %}
        </div>
    </div>
    <a href="{% url 'forum_app:forum' %}" class="btn btn-success" role="button">
        Back to Forum</a><br />
        <br /><br />
</div>

{% endblock %}